package com.rule

import com.javainuse.model.Character
rule "High Hp"
    when
    		CharacterObject: Character(hp>=60)
    then
    		System.out.println("Receive little damage!");
    end

rule "Low HP"
	when 
		CharacterObject: Character(hp<=30)
	then
		System.out.println("Player need to do something right now!");
	end
rule "Hp zeros"
	when 
		CharacterObject: Character(hp==0)
	then
		System.out.println("Nice shot and it confirms the round!");
	end
rule "Use sp"
    when
        CharacterObject: Character(sp<=30)

    then
        System.out.println("play used ultimate attack!");
     end